import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import Navbar from "./_components/Navbar";
import { ToastContainer } from "react-toastify";
import { AuthProvider } from "./lib/context/AuthContext";

// Initialize fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Note: 'metadata' is TypeScript/Next.js-specific, you can remove or ignore it in pure JSX
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Theme>
          <AuthProvider>
            <Navbar />

            {children}
          </AuthProvider>

          <ToastContainer position="top-right" autoClose={3000} />
        </Theme>
      </body>
    </html>
  );
}
